name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is ${env:BUILD_NUMBER}"
      
    - uses: actions/checkout@v1
    - name: Import required modules
      run: Install-Module -Name InvokeBuild, PlatyPS, PowerShellGet, Pester -SkipPublisherCheck -Force
      shell: powershell
    - name: Run Pester tests
      run: |
        $ErrorActionPreference = 'Stop'
        invoke-build -File .\Build\Snow.SnowAutomationPlatform.ServiceNow.Integration.BUILD.ps1
      shell: powershell
